server:
  port: 8001

spring:
  application:
    name: microserviercloud-provider-dept
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: zh199609
    url: jdbc:mysql://119.29.238.123:3306/springcloud01?useUnicode=true&characterEncoding=utf8
mybatis:
  configuration:
    map-underscore-to-camel-case: true
eureka:
  client: #客户端注册进eureka服务列表
    service-url:
      defaultZone:  http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept-8001
    prefer-ip-address: true

info:
  app.name: zl-cloud
  company.name: www.zl77.cn
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
